[project]
name = "llm2sh"
description = "Ask GPT to run a command"
dynamic = ["version"]
license = {text = "GPL-3.0"}
requires-python = ">=3.8"
readme = "README.md"
authors = [{name = "David Li", email = "david@david-li.com"}]
keywords = ["llm", "gpt", "cli"]
dependencies = [
  "openai>=1.30.5",
  "anthropic",
]

[project.optional-dependencies]
dev = ["build", "twine"]

[project.scripts]
llm2sh = "llm2sh.__main__:cli"

[tool.setuptools.dynamic]
version = { file = ".latest-version-python.generated.txt" }

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
"Changelog" = "https://github.com/randombk/llm2sh/blob/master/.version"
"Source" = "https://github.com/randombk/llm2sh"
"Tracker" = "https://github.com/randombk/llm2sh/issues"
